"""Public API for uniqdiff."""

from uniqdiff.bloom import BloomFilter, build_bloom_filter, probabilistic_diff_candidates
from uniqdiff.connectors import (
    ConnectorRegistry,
    CSVConnector,
    FileConnector,
    IterableConnector,
    JSONLConnector,
    ParquetConnector,
    SourceConnector,
    TextConnector,
    TSVConnector,
    connect,
    create_connector,
    list_connectors,
    register_connector,
)
from uniqdiff.core import (
    compare,
    compare_by_hash,
    compare_by_key,
    compare_fields,
    compare_fields_files,
    compare_fields_files_sorted,
    compare_fields_sorted,
    compare_file_fields,
    compare_file_fields_sorted,
    compare_file_schema,
    compare_files,
    compare_iter,
    compare_schema,
    compare_sorted_iter,
    compare_sources,
    compare_streams,
    diff,
    duplicates,
    duplicates_source,
    infer_schema,
    intersection,
    iter_compare_events,
    iter_field_diff_events,
    iter_field_diff_sorted,
    iter_sorted_field_diff_events,
    unique,
    write_sorted_diff_file,
)
from uniqdiff.exceptions import (
    ComparatorError,
    CorruptedInputError,
    DiskLimitExceededError,
    InvalidInputError,
    KeyExtractionError,
    MissingOptionalDependencyError,
    NormalizationError,
    TempStorageError,
    UniqDiffError,
    UnsupportedFormatError,
)
from uniqdiff.fields import FieldChange, FieldDiffResult, FieldDiffStats, iter_field_diff_rows
from uniqdiff.fuzzy import compare_fuzzy_strings
from uniqdiff.normalizers import compose_normalizers, string_normalizer
from uniqdiff.output import (
    EventSummary,
    iter_event_rows,
    iter_result_rows,
    iter_result_values,
    summarize_event_file,
    summarize_events,
)
from uniqdiff.result import CompareResult, CompareStats
from uniqdiff.schema import ColumnSchema, SchemaDiffResult, SchemaResult
from uniqdiff.streaming import iter_sorted_diff, write_sorted_diff

__all__ = [
    "ComparatorError",
    "BloomFilter",
    "CSVConnector",
    "ColumnSchema",
    "ConnectorRegistry",
    "CompareResult",
    "CompareStats",
    "CorruptedInputError",
    "DiskLimitExceededError",
    "EventSummary",
    "FileConnector",
    "FieldChange",
    "FieldDiffResult",
    "FieldDiffStats",
    "InvalidInputError",
    "IterableConnector",
    "JSONLConnector",
    "KeyExtractionError",
    "MissingOptionalDependencyError",
    "NormalizationError",
    "ParquetConnector",
    "SchemaDiffResult",
    "SchemaResult",
    "SourceConnector",
    "TSVConnector",
    "TempStorageError",
    "TextConnector",
    "UniqDiffError",
    "UnsupportedFormatError",
    "build_bloom_filter",
    "connect",
    "compare",
    "compare_fields",
    "compare_fields_files_sorted",
    "compare_fields_sorted",
    "compare_file_fields",
    "compare_file_fields_sorted",
    "compare_file_schema",
    "compare_fields_files",
    "compare_by_hash",
    "compare_by_key",
    "compare_files",
    "compare_fuzzy_strings",
    "compare_iter",
    "compare_schema",
    "compare_sources",
    "compare_sorted_iter",
    "compare_streams",
    "compose_normalizers",
    "create_connector",
    "diff",
    "duplicates",
    "duplicates_source",
    "infer_schema",
    "intersection",
    "iter_compare_events",
    "iter_field_diff_events",
    "iter_event_rows",
    "iter_field_diff_sorted",
    "iter_result_rows",
    "iter_result_values",
    "iter_field_diff_rows",
    "iter_sorted_field_diff_events",
    "iter_sorted_diff",
    "list_connectors",
    "probabilistic_diff_candidates",
    "register_connector",
    "string_normalizer",
    "summarize_event_file",
    "summarize_events",
    "unique",
    "write_sorted_diff",
    "write_sorted_diff_file",
]
