"""Public API for uniqdiff."""

from uniqdiff.bloom import BloomFilter, build_bloom_filter, probabilistic_diff_candidates
from uniqdiff.connectors import (
    ConnectorRegistry,
    CSVConnector,
    FileConnector,
    IterableConnector,
    JSONLConnector,
    ParquetConnector,
    SourceConnector,
    TextConnector,
    TSVConnector,
    connect,
    create_connector,
    list_connectors,
    register_connector,
)
from uniqdiff.core import (
    compare,
    compare_by_hash,
    compare_by_key,
    compare_files,
    compare_iter,
    compare_sources,
    compare_streams,
    diff,
    duplicates,
    duplicates_source,
    intersection,
    unique,
)
from uniqdiff.exceptions import (
    ComparatorError,
    CorruptedInputError,
    DiskLimitExceededError,
    InvalidInputError,
    KeyExtractionError,
    MissingOptionalDependencyError,
    NormalizationError,
    TempStorageError,
    UniqDiffError,
    UnsupportedFormatError,
)
from uniqdiff.fuzzy import compare_fuzzy_strings
from uniqdiff.normalizers import compose_normalizers, string_normalizer
from uniqdiff.output import iter_result_rows, iter_result_values
from uniqdiff.result import CompareResult, CompareStats
from uniqdiff.streaming import iter_sorted_diff

__all__ = [
    "ComparatorError",
    "BloomFilter",
    "CSVConnector",
    "ConnectorRegistry",
    "CompareResult",
    "CompareStats",
    "CorruptedInputError",
    "DiskLimitExceededError",
    "FileConnector",
    "InvalidInputError",
    "IterableConnector",
    "JSONLConnector",
    "KeyExtractionError",
    "MissingOptionalDependencyError",
    "NormalizationError",
    "ParquetConnector",
    "SourceConnector",
    "TSVConnector",
    "TempStorageError",
    "TextConnector",
    "UniqDiffError",
    "UnsupportedFormatError",
    "build_bloom_filter",
    "connect",
    "compare",
    "compare_by_hash",
    "compare_by_key",
    "compare_files",
    "compare_fuzzy_strings",
    "compare_iter",
    "compare_sources",
    "compare_streams",
    "compose_normalizers",
    "create_connector",
    "diff",
    "duplicates",
    "duplicates_source",
    "intersection",
    "iter_result_rows",
    "iter_result_values",
    "iter_sorted_diff",
    "list_connectors",
    "probabilistic_diff_candidates",
    "register_connector",
    "string_normalizer",
    "unique",
]
